# Comand to run when starting the bot.
# Argv style also supported: ["python", "simplebot.py"]
command = "python bot.py"

# Directory in which to run the command.
# It is recommended to use an absolute path here.
working_directory = "."